apiVersion: v1
kind: ConfigMap
metadata:
  name: leafyhealth-config
  namespace: leafyhealth
data:
  NODE_ENV: "production"
  REDIS_URL: "redis://redis-service:6379"
  DATABASE_URL: "postgresql://postgres:postgres@postgres-service:5432/leafyhealth"
---
apiVersion: v1
kind: Secret
metadata:
  name: leafyhealth-secrets
  namespace: leafyhealth
type: Opaque
stringData:
  postgres-db: leafyhealth
  postgres-user: postgres
  postgres-password: your_secure_password_here
  jwt-secret: your_32_character_jwt_secret_here
  acme-email: admin@yourdomain.com